### ISSUE TITLE
filePath всегда null

### ISSUE THREAD

**Issue by Intey** [SinorTomato/FileProj#2]
https://github.com/SinorTomato/FileProj/blob/b93c9c43f87462c78c9b4238218dc5e794c703d9/FirstTask/Program.cs#L10
при запуске, в `ReaderAndOutputer` попадет строка которая null. Смысл в этом? Если функция/конструктор принимает строку, то она должна передаваться с определенным значением.
Судя по коду, в `FileGenerator` строка будет заменена на `_Path = $"{AppDomain.CurrentDomain.BaseDirectory}file.txt";`. Это в целом решает проблему, не это больше костыль. А если захочется поменять путь к файлу, то как быть? перекомпилить? 
Значение по умолчанию лучше указывать в настройках. На крайняк - в Main.
В `Main` брать путь к файлу из аргументов. Если аргументов нет - брать значение по-умолчанию.

**Comment by SinorTomato** [comment]
В мэине переменная директории, которая проверяется на наличие файла, если его не существует, создаётся новый файл в дебаге, а нул там для проверки, что он его проглотит и не упадёт
